---
galaxy_info:
  role_name: bind_zone_manager
  author: Morten Victor Nordbye
  description: "Manage BIND forward and reverse DNS zones with customizable A and CNAME records."
  license: Apache-2.0
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble

dependencies: []
