apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-pvc
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: syno-nfs
  resources:
    requests:
      storage: 1Gi
