global:
  checkNewVersion: false
  sendAnonymousUsage: false

additionalArguments:
  - "--serverstransport.insecureskipverify=true"

deployment:
  enabled: true
  replicas: 2
  revisionHistoryLimit: 2

logs:
  general:
    level: INFO
  access:
    enabled: false

ports:
  web:
    port: 80
    expose:
      default: true
    exposedPort: 80

  websecure:
    port: 443
    expose:
      default: true
    exposedPort: 443
    http3:
      enabled: true
      advertisedPort: 443
    tls:
      enabled: true

  ssh:
    port: 2222
    expose:
      default: true
    exposedPort: 2222
    protocol: TCP

  metrics:
    port: 8082
    expose:
      default: false
    exposedPort: 8082

ingressRoute:
  dashboard:
    enabled: false

metrics:
  prometheus:
    entryPoint: metrics
    service:
      enabled: true
      labels:
        Release: kube-prometheus-stack
      annotations: {}
    serviceMonitor:
      enabled: true
      namespace: monitoring
      namespaceSelector:
        matchNames:
          - traefik
      additionalLabels:
        Release: kube-prometheus-stack
      interval: 30s
      scrapeTimeout: 10s

providers:
  kubernetesCRD:
    enabled: true
    ingressClass: traefik
    allowExternalNameServices: true
    allowCrossNamespace: true

  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    publishedService:
      pathOverride: traefik/traefik

rbac:
  enabled: true

service:
  enabled: true
  type: LoadBalancer
  spec:
    loadBalancerIP: 10.0.0.58