import { tex } from "./escape";
import { period, skillGroupLabel } from "./format";
import type {
  Cert,
  Education,
  Experience,
  Skill,
  WorkFrontmatter,
} from "@/content/schemas";
import type { SectionId, Variant } from "@/content/cv-variants";

type SiteForLatex = {
  firstName: string;
  lastName: string;
  role: string;
  cvAddress: string;
  phoneLatex: string;
  email: string;
  homepage: string;
  github: string;
  linkedin: string;
};

const HEADER_NOTE = `% This file is auto-generated by scripts/build-cv.ts — do not edit by hand.\n% Edit the content in portfolio-modern/src/content/* and run \`make cv-gen\`.\n`;

/* ------------------------------------------------------------------------- */
/* Entry-point .tex (one per variant)                                        */
/* ------------------------------------------------------------------------- */

// All section .tex files are emitted once under latex/cv/ and shared across
// the 16 customizable CV variants. The résumé variant has its own set under
// latex/resume/ because a few section files render differently (the résumé
// drops the lead summary paragraph repetition, etc.). For sections that
// exist in both directories the résumé variant picks the resume/ flavor.
function inputPathFor(variant: Variant, section: SectionId): string {
  const root = variant.id === "resume" ? "resume" : "cv";
  return `${root}/${section}.tex`;
}

export function renderEntryPoint(variant: Variant, site: SiteForLatex): string {
  const includes = variant.sections.map((s) => inputPathFor(variant, s));
  const photoLine = variant.photo
    ? "\\photo[circle,edge,right]{profile.jpg}\n"
    : "";

  return `${HEADER_NOTE}%!TEX TS-program = xelatex
%!TEX encoding = UTF-8 Unicode
% Awesome-CV — generated entry point for ${variant.id}.

\\documentclass[11pt, a4paper]{awesome-cv}

\\geometry{left=1.4cm, top=.8cm, right=1.4cm, bottom=1.8cm, footskip=.5cm}

\\fontdir[fonts/]

\\colorlet{awesome}{awesome-skyblue}
\\setbool{acvSectionColorHighlight}{true}
\\renewcommand{\\acvHeaderSocialSep}{\\quad\\textbar\\quad}

% Compact cv entry without the trailing description row. Used for items that
% have a title + issuer + date but no bullet body (e.g. certifications). This
% matches the look of \\cventry exactly but skips the empty multicolumn row
% that would otherwise leave vertical padding underneath.
\\newcommand*{\\cventrycompact}[4]{%
  \\vspace{-2.0mm}
  \\setlength\\tabcolsep{0pt}
  \\setlength{\\extrarowheight}{0pt}
  \\begin{tabular*}{\\textwidth}{@{\\extracolsep{\\fill}} L{\\textwidth - 4.5cm} R{4.5cm}}
    \\ifempty{#2#3}
      {\\entrypositionstyle{#1} & \\entrydatestyle{#4} \\\\}
      {\\entrytitlestyle{#2} & \\entrylocationstyle{#3} \\\\
      \\entrypositionstyle{#1} & \\entrydatestyle{#4} \\\\}
  \\end{tabular*}%
}

%-------------------------------------------------------------------------------
%	PERSONAL INFORMATION
%-------------------------------------------------------------------------------
\\name{${tex(site.firstName)}}{${tex(site.lastName)}}
\\position{${tex(site.role)}}
\\address{${tex(site.cvAddress)}}
\\mobile{${tex(site.phoneLatex)}}
\\email{${tex(site.email)}}
\\homepage{${tex(site.homepage)}}
\\github{github.com/${tex(site.github)}}
\\linkedin{linkedin.com/in/${tex(site.linkedin)}}
${photoLine}
%-------------------------------------------------------------------------------
\\begin{document}

\\makecvheader[C]
\\makecvfooter
  {\\today}
  {${variant.footerLabel}}
  {\\thepage}

%-------------------------------------------------------------------------------
%	CONTENT
%-------------------------------------------------------------------------------
${includes.map((p) => `\\input{${p}}`).join("\n")}

\\end{document}
`;
}

/* ------------------------------------------------------------------------- */
/* Section files                                                             */
/* ------------------------------------------------------------------------- */

export function renderSummary(text: string): string {
  return `${HEADER_NOTE}\\cvsection{Summary}

\\begin{cvparagraph}

${tex(text)}

\\end{cvparagraph}
`;
}

function cvitems(lines: string[]): string {
  if (!lines.length) {
    return "      \\begin{cvitems}\n        \\item {}\n      \\end{cvitems}";
  }
  return [
    "      \\begin{cvitems}",
    ...lines.map((l) => `        \\item {${tex(l)}}`),
    "      \\end{cvitems}",
  ].join("\n");
}

function cventry(opts: {
  title: string;
  org: string;
  location: string;
  period: string;
  items: string[];
}): string {
  // When there are no bullet items (e.g. a cert without a credential ID),
  // pass an empty body instead of an empty cvitems list — otherwise
  // awesome-cv renders an orphaned bullet point.
  const body =
    opts.items.length > 0 ? `\n${cvitems(opts.items)}\n    ` : "";
  return `  \\cventry
    {${tex(opts.title)}}
    {${tex(opts.org)}}
    {${tex(opts.location)}}
    {${tex(opts.period)}}
    {${body}}`;
}

export function renderExperience(items: Experience[]): string {
  const entries = items
    .map((e) => {
      const lines = Array.isArray(e.description) ? e.description : [e.description];
      return cventry({
        title: e.role,
        org: e.company,
        location: e.location ?? "",
        period: period(e.period),
        items: lines,
      });
    })
    .join("\n\n  \\vspace{4mm}\n%---------------------------------------------------------\n");

  return `${HEADER_NOTE}\\cvsection{Work Experience}

\\begin{cventries}

%---------------------------------------------------------
${entries}

%---------------------------------------------------------
\\end{cventries}
`;
}

/**
 * Render a projects section for the full CV. Each entry is the project's
 * title + client + role + period, followed by the project summary as the
 * lead bullet and up to N outcome bullets. The section title is configurable
 * so the same renderer drives both the professional "Selected Projects"
 * section and the "Home Lab Projects" section.
 */
export function renderProjects(
  items: WorkFrontmatter[],
  opts: { title?: string; maxOutcomes?: number } = {},
): string {
  const sectionTitle = opts.title ?? "Selected Projects";
  const maxOutcomes = opts.maxOutcomes ?? 3;

  const entries = items
    .map((p) => {
      const bullets = [p.summary, ...p.outcomes.slice(0, maxOutcomes)];
      return cventry({
        title: p.title,
        org: p.client,
        location: p.role,
        period: period(p.period),
        items: bullets,
      });
    })
    .join("\n\n  \\vspace{4mm}\n%---------------------------------------------------------\n");

  return `${HEADER_NOTE}\\cvsection{${tex(sectionTitle)}}

\\begin{cventries}

%---------------------------------------------------------
${entries}

%---------------------------------------------------------
\\end{cventries}
`;
}

export function renderEducation(items: Education[]): string {
  const entries = items
    .map((e) =>
      cventry({
        title: e.title,
        org: e.institution,
        location: "",
        period: period(e.period),
        items: e.detail ? [e.detail] : [],
      }),
    )
    .join("\n\n  \\vspace{4mm}\n%---------------------------------------------------------\n");

  return `${HEADER_NOTE}\\cvsection{Education}

\\begin{cventries}

%---------------------------------------------------------
${entries}

%---------------------------------------------------------
\\end{cventries}
`;
}

export function renderCertifications(items: Cert[]): string {
  const entries = items
    .map((c) => {
      // Credential ID, when present, sits in the title as a faint suffix —
      // visually consistent with the rest of the CV's entries.
      const titleWithId = c.credentialId
        ? `${tex(c.title)} \\textnormal{\\textcolor{darkgray}{(${tex(c.credentialId)})}}`
        : tex(c.title);
      return `  \\cventrycompact
    {${tex(c.issuer)}}
    {${titleWithId}}
    {}
    {${tex(`Issued ${c.date}`)}}`;
    })
    .join("\n\n%---------------------------------------------------------\n");

  return `${HEADER_NOTE}\\cvsection{Certifications}

\\begin{cventries}

%---------------------------------------------------------
${entries}

%---------------------------------------------------------
\\end{cventries}
`;
}

export function renderSkills(skills: Skill[]): string {
  const groupOrder = ["platform", "delivery", "ops", "soft"];
  const grouped = new Map<string, string[]>();
  for (const s of skills) {
    const arr = grouped.get(s.group) ?? [];
    arr.push(s.label);
    grouped.set(s.group, arr);
  }

  // Skills sit inside a `tabular*`. Inserting \vspace between rows breaks
  // the table layout, so just use a plain comment separator here — no spacer.
  const blocks = groupOrder
    .filter((g) => grouped.has(g))
    .map(
      (g) =>
        `  \\cvskill\n    {${tex(skillGroupLabel(g))}}\n    {${(grouped.get(g) ?? [])
          .map((l) => tex(l))
          .join(", ")}}`,
    )
    .join("\n%---------------------------------------------------------\n");

  return `${HEADER_NOTE}\\cvsection{Skills}

\\begin{cvskills}

%---------------------------------------------------------
${blocks}

%---------------------------------------------------------
\\end{cvskills}
`;
}
