---
- name: Ensure we're on Ubuntu
  when: >
    ansible_distribution == 'Ubuntu'
  tags: update
  ansible.builtin.assert:
    that:
      - ansible_distribution == 'Ubuntu'
    fail_msg: "This role only supports Ubuntu"

- name: Update apt cache
  when: update_ubuntu_cache_valid_time > 0
  tags: update
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ update_ubuntu_cache_valid_time }}"

- name: Upgrade packages
  when: update_ubuntu_do_upgrade
  tags: upgrade
  register: upgrade_result
  ansible.builtin.apt:
    upgrade: "{{ update_ubuntu_upgrade_type }}"

- name: Autoremove unused packages
  when: update_ubuntu_do_autoremove
  tags: cleanup
  ansible.builtin.apt:
    autoremove: true

- name: Autoclean apt cache
  when: update_ubuntu_do_autoclean
  tags: cleanup
  ansible.builtin.apt:
    autoclean: true

- name: Check if reboot is required
  tags: reboot
  register: reboot_required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  changed_when: false

- name: Trigger reboot handler
  when:
    - update_ubuntu_auto_reboot
    - reboot_required.stat.exists
  tags: reboot
  ansible.builtin.meta: flush_handlers
