apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gatus-discord-webhook-secret
  namespace: gatus
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: gatus-discord-webhook-secret
    creationPolicy: Owner
  data:
    - secretKey: DISCORD_WEBHOOK_URL
      remoteRef:
        key: "1c16150b-bfc8-4064-ad65-b2a201197373"
