apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: portfolio-stage
  namespace: stage-portfolio
spec:
  scaleTargetRef:
    name: portfolio-stage
  minReplicaCount: 0
  maxReplicaCount: 1
  cooldownPeriod: 300
  triggers:
    - type: cron
      metadata:
        timezone: Europe/Oslo
        start: "0 7 * * *"
        end: "0 23 * * *"
        desiredReplicas: "1"
