apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arc-github-token
  namespace: arc-runners
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: arc-github-token
    creationPolicy: Owner
  data:
    - secretKey: github_token
      remoteRef:
        key: "c67eb804-9345-46c5-9b7a-b2cb00cd3070"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
