deploymentMode: SingleBinary

authentik:
  existingSecret: 
    secretName: "authentik-secrets"
  secret_key: "" 
  env:
    - name: AUTHENTIK_POSTGRESQL__HOST
      value: "authentik-postgresql"
    - name: AUTHENTIK_POSTGRESQL__USER
      value: "authentik"
    - name: AUTHENTIK_POSTGRESQL__NAME
      value: "authentik"
    - name: AUTHENTIK_POSTGRESQL__PORT
      value: "5432"
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-secrets
          key: postgres-password
  postgresql:
    host: "authentik-postgresql"
    name: "authentik"
    user: "authentik"
  redis:
    enabled: false

postgresql:
  enabled: true
  auth:
    existingSecret: "authentik-secrets"
    secretKeys:
      adminPasswordKey: "postgres-password"
      userPasswordKey: "postgres-password"
  persistence:
    enabled: true
    storageClass: "syno-nfs-csi"
    size: 8Gi
    accessModes:
      - ReadWriteOnce

server:
  route:
    main:
      enabled: true
      hostnames:
        - "auth.local.bigd.no"
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: traefik-gateway-private
          namespace: traefik

worker:
  replicas: 1

error_reporting:
  enabled: false