deploymentMode: SingleBinary

authentik:
  existingSecret: 
    secretName: "authentik-secrets"
  secret_key: "" 
  
  postgresql:
    host: "authentik-postgresql"
    name: "authentik"
    user: "authentik"

  redis:
    enabled: false

postgresql:
  enabled: true
  auth:
    existingSecret: "authentik-secrets"
    secretKeys:
      adminPasswordKey: "postgres-password"
      userPasswordKey: "postgres-password"
  persistence:
    enabled: true
    storageClass: "syno-nfs-csi"
    size: 8Gi
    accessModes:
      - ReadWriteOnce

server:
  route:
    main:
      enabled: true
      hostnames:
        - "auth.local.bigd.no"
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: traefik-gateway-private
          namespace: traefik

worker:
  replicas: 1

error_reporting:
  enabled: false