serviceAccount:
  create: true

rbac:
  create: true

controller:
  kind: daemonset

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane

tty: false

driver:
  enabled: true
  kind: modern_ebpf
  modernEbpf:
    leastPrivileged: true
    bufSizePreset: 4
    dropFailedExit: false
    cpusForEachBuffer: 2
  loader:
    enabled: true

collectors:
  enabled: true
  containerEngine:
    enabled: true
    labelMaxLen: 100
    withSize: false
    hooks: ["create"]
    engines:
      cri:
        enabled: true
        sockets: ["/run/k3s/containerd/containerd.sock"]
      containerd:
        enabled: false

falco:
  rules_files:
    - /etc/falco/falco_rules.yaml
    - /etc/falco/falco_rules.local.yaml
    - /etc/falco/rules.d
  rule_matching: first

  priority: notice
  json_output: true
  json_include_output_fields_property: true

  stdout_output:
    enabled: true
  syslog_output:
    enabled: false

  webserver:
    enabled: true
    listen_port: 8765
    prometheus_metrics_enabled: false
    ssl_enabled: false

  grpc:
    enabled: false
    bind_address: "unix:///run/falco/falco.sock"

metrics:
  enabled: false

serviceMonitor:
  create: false

falcosidekick:
  enabled: false
