apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: custom-ip-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.0.0.58-10.0.0.66
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: custom-l2-advertisement
  namespace: metallb-system
