apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-discord-webhook
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: alertmanager-discord-webhook
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: "d810abf7-40ad-4b1c-9d30-b44c0108ecad"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
