apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: gitlab-runner-secret
  namespace: gitlab-runner
spec:
  organizationId: "1a1f473f-c6a3-47af-a106-b29800f5ca1f"
  secretName: "gitlab-runner-secret"
  map:
    - bwSecretId: "b6068576-c0b6-4228-a43f-b29b010cd03d"
      secretKeyName: "runner-registration-token"
    - bwSecretId: "56b7da7c-4b53-40e8-b2ba-b29b010b75ef"
      secretKeyName: "runner-token"
  authToken:
    secretName: bw-auth-token
    secretKey: token
