apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-runner-secret
  namespace: gitlab-runner
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: gitlab-runner-secret
    creationPolicy: Owner
  data:
    - secretKey: runner-registration-token
      remoteRef:
        key: "b6068576-c0b6-4228-a43f-b29b010cd03d"
    - secretKey: runner-token
      remoteRef:
        key: "56b7da7c-4b53-40e8-b2ba-b29b010b75ef"
