apiVersion: v1
kind: Service
metadata:
  name: proxmox-service
  namespace: traefik
spec:
  type: ClusterIP
  ports:
    - name: proxmox
      protocol: TCP
      port: 8006
      targetPort: 8006
---
apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox-service
  namespace: traefik
subsets:
  - addresses:
      - ip: 10.0.0.4
    ports:
      - name: proxmox
        port: 8006
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: proxmox-ingress
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`hyper1.local.bigd.no`)
      services:
        - name: proxmox-service
          port: 8006
  tls:
    secretName: local-bigd-no-tls
