apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-stage
  annotations:
        argocd.argoproj.io/sync-wave: "100"
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: morten@nordbye.it
    privateKeySecretRef:
      name: letsencrypt-stage
    solvers:
      - dns01:
          cloudflare:
            email: morten@nordbye.it
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: cloudflare-token
        selector:
          dnsZones:
            - "bigd.no"
