apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - crd.yaml
  - deployment.yaml
  - namespace.yaml
  - serviceaccount.yaml
  - upgrade-to-stable-channel.yaml