services:
  plex:
    image: ghcr.io/linuxserver/plex:latest
    container_name: plex
    env_file: .env
    network_mode: host
    restart: unless-stopped
    environment:
      PUID:        ${PUID}
      PGID:        ${PGID}
      TZ:          ${TZ}
      VERSION:     ${VERSION}
      PLEX_CLAIM:  ${PLEX_CLAIM}
    volumes:
      - ./volumes/plex/config:/config
      - ${MEDIA_ROOT}/series:/tv
      - ${MEDIA_ROOT}/movies:/movies
      - ${MEDIA_ROOT}/courses:/courses
      - ${MEDIA_ROOT}/youtube:/youtube
      - /tmp/plex:/transcode:rw,noexec,nosuid
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:32400/identity || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  tautulli:
    image: ghcr.io/linuxserver/tautulli:latest
    container_name: tautulli
    env_file: .env
    network_mode: host
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ:   ${TZ}
    volumes:
      - ./volumes/tautulli/config:/config
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8181/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  overseerr:
    image: ghcr.io/linuxserver/overseerr:latest
    container_name: overseerr
    env_file:
      - .env
    network_mode: host
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./volumes/overseerr/config:/config
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5055/api/v1/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
