apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: trek
  namespace: trek
spec:
  target:
    service: trek-service
    port: 3000
  rules:
    - hosts:
        - trek.bigd.no
  scalingMetric:
    concurrency:
      targetValue: 100
