apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - alertmanager-discord-webhook-ext-secret.yaml
  - grafana-admin-creds-ext-secret.yaml
  - grafana-ingressroute.yaml
  - prometheus-ingressroute.yaml
  - prometheusrule-disk-alerts.yaml
  
namespace: monitoring

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    includeCRDs: false
    namespace: monitoring
    version: 75.18.1
    releaseName: kube-prometheus-stack
    valuesFile: ./values.yaml