---
- name: Update Phase 1 servers
  hosts: phase1
  become: yes
  roles:
    - role: update_ubuntu

- name: Rest Period 1
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Pause 1 minute before next phase
      ansible.builtin.pause:
        minutes: 1

- name: Update Phase 2 servers
  hosts: phase2
  become: yes
  roles:
    - role: update_ubuntu

- name: Rest Period 2
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Pause 2 minutes before next phase
      ansible.builtin.pause:
        minutes: 2

- name: Update Phase 3 servers
  hosts: phase3
  become: yes
  roles:
    - role: update_ubuntu

- name: Rest before K8s masters
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Pause 5 minutes before Kubernetes updates
      ansible.builtin.pause:
        minutes: 5

- name: Update Kubernetes master nodes (one at a time)
  hosts: k8s_masters
  become: yes
  serial: 1
  roles:
    - role: update_ubuntu

- name: Rest before K8s workers
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Pause 10 minutes before updating Kubernetes workers
      ansible.builtin.pause:
        minutes: 10

- name: Update Kubernetes worker nodes (one at a time)
  hosts: k8s_workers
  become: yes
  serial: 1
  roles:
    - role: update_ubuntu

- name: Rest before DNS/BIND update
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Pause 10 minutes before updating BIND servers
      ansible.builtin.pause:
        minutes: 10

- name: Update Phase 4 servers (DNS/BIND)
  hosts: phase4
  become: yes
  roles:
    - role: update_ubuntu
