# Where a volume lives for each kind of claim. See platform/storage/README.md.
direction: down
vars: {
  di: https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg
  k8s: https://raw.githubusercontent.com/kubernetes/community/master/icons/svg/resources/unlabeled
  ify: https://api.iconify.design
}

style.fill: "#0f1410"

classes: {
  card: {
    label.near: bottom-center
    style: {fill: "#191f1a"; stroke: "#2a382c"; font-color: "#e9ebe9"; border-radius: 8; font-size: 16}
  }
  aside: {
    label.near: bottom-center
    style: {fill: "#0f1410"; stroke: "#c09955"; stroke-dash: 4; font-color: "#a1ada3"; border-radius: 8; font-size: 14}
  }
}

(** -> **)[*].style: {stroke: "#65a16e"; font-color: "#a1ada3"; font-size: 14}

classes.group: {
  label.near: top-left
  style: {fill: "#0f1410"; stroke: "#2a382c"; font-color: "#a1ada3"; border-radius: 12; font-size: 15}
}

pvc: "PersistentVolumeClaim" {class: card; icon: ${k8s}/pvc.svg; width: 210}
inline: "inline nfs volume\nmedia apps,\naudiobookshelf,\nverksted" {class: card; icon: ${k8s}/pod.svg; width: 175}

local: "proxmox-local\ndefault class\nWaitForFirstConsumer" {class: card; icon: ${k8s}/sc.svg; width: 210}
nfs: "syno-nfs-csi\nImmediate\nonDelete: archive" {class: card; icon: ${k8s}/sc.svg; width: 175}
static: "static PV\nRetain, claimRef" {class: card; icon: ${k8s}/pv.svg; width: 175}

pxcsi: "Proxmox CSI\nkubernetes-csi@pve" {class: card; icon: ${di}/proxmox-light.svg; width: 175}
nfscsi: "csi-driver-nfs" {class: card; icon: ${di}/kubernetes.svg; width: 175}

host: Proxmox hosts {
  class: group
  disk: "vm-9999-pvc-<uid>\nlocal-lvm" {class: card; icon: ${di}/proxmox-light.svg; width: 175}
  vm: "Talos VM\nof the first pod" {class: card; icon: ${di}/talos.svg; width: 175}
}

nas: Synology NAS {
  class: group
  vols: "k8s-volumes/talos\n<ns>/<pvc>" {class: card; icon: ${di}/synology.svg; width: 175}
  backups: "k8s-backups\netcd, postgres\ndumps" {class: card; icon: ${di}/synology.svg; width: 175}
  shared: "shared-data\nmedia, reelsmith" {class: card; icon: ${di}/synology.svg; width: 175}
}

pvc -> local
pvc -> nfs
pvc -> static
local -> pxcsi -> host.disk
host.disk -> host.vm: hot-plugged
nfs -> nfscsi -> nas.vols
static -> nas.backups
static -> nas.shared
inline -> nas.shared
