apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: app-httproutes-to-interceptor
  namespace: keda
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: stage-portfolio
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: stage-blog
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: it-tools
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: omni-tools
  to:
    - group: ""
      kind: Service
