apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: argocd-gitlab-creds
  namespace: argo-cd
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  organizationId: "1a1f473f-c6a3-47af-a106-b29800f5ca1f"
  secretName: "argocd-gitlab-creds"
  map:
    - bwSecretId: "c351bc74-4e12-4fe1-9e71-b29b011366be"
      secretKeyName: "username"
    - bwSecretId: "bebf5412-f1bb-40d3-8c2c-b29b014a9fb4"
      secretKeyName: "password"
  authToken:
    secretName: bw-auth-token
    secretKey: token
