apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: open-webui
  namespace: open-webui
spec:
  target:
    service: open-webui-service
    port: 8080
  rules:
    - hosts:
        - open-webui.local.bigd.no
  scalingMetric:
    concurrency:
      targetValue: 100
