services:
  db:
    image: "${POSTGRES_IMAGE}"
    restart: unless-stopped
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER:        "${POSTGRES_USER}"
      POSTGRES_PASSWORD:    "${POSTGRES_PASSWORD}"
      POSTGRES_INITDB_ARGS: "${POSTGRES_INITDB_ARGS}"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - pg-network

  pgadmin:
    image: "${PGADMIN_IMAGE}"
    restart: unless-stopped
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL:    "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - pg-network

volumes:
  db_data:
  pgadmin_data:

networks:
  pg-network:
