---
galaxy_info:
  role_name: update_server
  author: Morten Victor Nordbye
  description: "Refresh apt cache, upgrade packages, clean up and reboot on Ubuntu servers"
  license: Apache-2.0
  min_ansible_version: "2.11"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble

dependencies: []
