apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argo-cd
spec:
  generators:
    - git:
        repoURL: https://github.com/mortennordbye/Homelab.git
        revision: HEAD
        directories:
          - path: k8s/k3sa/apps/*
  template:
    metadata:
      name: "{{ path.basename }}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: applications
      source:
        repoURL: https://github.com/mortennordbye/Homelab.git
        targetRevision: HEAD
        path: "{{ path }}"
      destination:
        name: in-cluster
        namespace: argo-cd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 1
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - PruneLast=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
