apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  namespace: argo-cd
  name: apps
  labels:
    app.kubernetes.io/part-of: apps
    app.kubernetes.io/managed-by: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  generators:
    - git:
        repoURL: https://github.com/mortennordbye/Homelab.git
        revision: main
        directories:
          - path: k8s/k3sa/apps/tools
  template:
    metadata:
      name: 'apps-{{ path.basename }}'
      namespace: argo-cd
      labels:
        app.kubernetes.io/component: 'static-apps'
        app.kubernetes.io/part-of: apps
    spec:
      project: apps
      source:
        repoURL: https://github.com/mortennordbye/Homelab.git
        targetRevision: main
        path: '{{ path }}'
        kustomize: {} # Let Kustomize handle naming
      destination:
        namespace: apps-system
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 1
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - PruneLast=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true