apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: omni-tools
  namespace: omni-tools
spec:
  target:
    service: omni-tools-service
    port: 80
  rules:
    - hosts:
        - omni-tools.bigd.no
  scalingMetric:
    concurrency:
      targetValue: 100
