apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: omni-tools
  namespace: omni-tools
spec:
  scaleTargetRef:
    name: omni-tools
  minReplicaCount: 0
  maxReplicaCount: 1
  cooldownPeriod: 300
  triggers:
    - type: external-push
      metadata:
        scalerAddress: keda-add-ons-http-external-scaler.keda:9090
        interceptorRoute: omni-tools
