{
 "title": "Homelab-SPOG",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": "label_values(cluster)" },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(node_uname_info{cluster=~\"$cluster\"}, nodename)"
   },
   {
    "name": "operation",
    "label": "operation",
    "query": "Average : 1, Minimum : 2, Maximum : 3"
   }
  ]
 },
 "panels": [
  {
   "title": "Traefik",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Global Request Rate (by Status Code)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(traefik_service_requests_total{cluster=~\"${cluster}\"}[5m])) by (code)",
       "legendFormat": "HTTP {{code}}"
      }
     ]
    },
    {
     "title": "Global 5xx Error Rate (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum(rate(traefik_service_requests_total{cluster=~\"${cluster}\", code=~\"5..\"}[5m])) / sum(rate(traefik_service_requests_total{cluster=~\"${cluster}\"}[5m]))) * 100",
       "legendFormat": "5xx Error Rate"
      }
     ]
    },
    {
     "title": "Global Routing Latency (P95 & P99)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(traefik_service_request_duration_seconds_bucket{cluster=~\"${cluster}\"}[5m])) by (le))",
       "legendFormat": "P99 Latency"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(traefik_service_request_duration_seconds_bucket{cluster=~\"${cluster}\"}[5m])) by (le))",
       "legendFormat": "P95 Latency"
      }
     ]
    },
    {
     "title": "Top 10 Services by Traffic",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "topk(10, sum by(service) (rate(traefik_service_requests_total{cluster=~\"${cluster}\", service!~\"prometheus@.*|ping@.*|noop@.*|^$\"}[5m])))",
       "legendFormat": "{{service}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cert-manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Certificate Readiness",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(certmanager_certificate_status_condition{cluster=~\"${cluster}\", condition=\"Ready\"}) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Certificate Expiration Tracker",
     "type": "table",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "d" } },
     "targets": [
      {
       "expr": "(certmanager_certificate_expiration_timestamp_seconds{cluster=~\"${cluster}\"} - time()) / 86400"
      }
     ]
    },
    {
     "title": "Cert-Manager Sync Errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "errs" } },
     "targets": [
      {
       "expr": "sum(rate(certmanager_controller_sync_calls_total{cluster=~\"${cluster}\", status=\"error\"}[5m])) by (controller)",
       "legendFormat": "{{controller}} Errors"
      }
     ]
    },
    {
     "title": "ACME Request Latency (P99)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(certmanager_http_acme_client_request_duration_seconds_bucket{cluster=~\"${cluster}\"}[5m])) by (le, host))",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  },
  { "title": "External-secrets-operator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Secret Sync Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(externalsecret_status_condition{cluster=~\"${cluster}\", condition=\"Ready\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Secret Sync Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(externalsecret_sync_calls_error{cluster=~\"${cluster}\"}[5m])) by (name, namespace)",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "Reconcile Latency (P99)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(controller_runtime_reconcile_time_seconds_bucket{controller=\"externalsecret\", cluster=~\"${cluster}\"}[5m])) by (le))",
     "legendFormat": "P99 Reconcile"
    }
   ]
  },
  {
   "title": "ESO Queue Depth",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(controller_runtime_reconcile_queue_length{controller=\"externalsecret\", cluster=~\"${cluster}\"})"
    }
   ]
  },
  { "title": "Argocd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Application Sync Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{cluster=~\"${cluster}\"}) by (sync_status)",
     "legendFormat": "{{sync_status}}"
    }
   ]
  },
  {
   "title": "Application Health Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{cluster=~\"${cluster}\"}) by (health_status)",
     "legendFormat": "{{health_status}}"
    }
   ]
  },
  {
   "title": "Reconciliation Rate (by Namespace)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(argocd_app_reconcile_count{cluster=~\"${cluster}\"}[5m])) by (dest_namespace)",
     "legendFormat": "{{dest_namespace}}"
    }
   ]
  },
  {
   "title": "Reconciliation Queue Depth",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(workqueue_depth{name=\"app_reconciliation_queue\", cluster=~\"${cluster}\"})",
     "legendFormat": "Queue Depth"
    }
   ]
  },
  { "title": "Cilium", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Cilium Network Drops (by Reason)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_drop_count_total{cluster=~\"${cluster}\"}[5m])) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Policy Import Success Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(cilium_kubernetes_events_total{status=\"success\", cluster=~\"${cluster}\"}) / sum(cilium_kubernetes_events_total{cluster=~\"${cluster}\"})) * 100"
    }
   ]
  },
  {
   "title": "Endpoint Regen Latency (P99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(cilium_endpoint_regeneration_time_seconds_bucket{cluster=~\"${cluster}\"}[5m])) by (le))",
     "legendFormat": "p99 Regen"
    }
   ]
  },
  {
   "title": "IPAM Pool Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cilium_ipam_usage{cluster=~\"${cluster}\"}",
     "legendFormat": "Pool: {{pool}}"
    }
   ]
  },
  {
   "title": "CoreDNS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "DNS Requests Rate (by Type)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(coredns_dns_requests_total{cluster=~\"${cluster}\"}[5m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "DNS Responses (by RCode)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(coredns_dns_responses_total{cluster=~\"${cluster}\"}[5m])) by (rcode)",
       "legendFormat": "{{rcode}}"
      }
     ]
    },
    {
     "title": "Cache Hit Ratio",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(rate(coredns_cache_hits_total{cluster=~\"${cluster}\"}[5m])) / (sum(rate(coredns_cache_hits_total{cluster=~\"${cluster}\"}[5m])) + sum(rate(coredns_cache_misses_total{cluster=~\"${cluster}\"}[5m])))) * 100",
       "legendFormat": "Hit Ratio"
      }
     ]
    },
    {
     "title": "P99 DNS Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 314 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_duration_seconds_bucket{cluster=~\"${cluster}\", zone=\"cluster.local.\"}[5m])) by (le))",
       "legendFormat": "Internal (cluster.local) p99"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_duration_seconds_bucket{cluster=~\"${cluster}\", zone=\".\"}[5m])) by (le))",
       "legendFormat": "External (Upstream) p99"
      }
     ]
    }
   ]
  },
  {
   "title": "Namespace Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage by Namespace",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "cores" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"${cluster}\", image!=\"\", container!=\"\"}[5m])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "CPU Limits by Namespace",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "cores" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", cluster=~\"${cluster}\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Memory Usage by Namespace",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{cluster=~\"${cluster}\", image!=\"\", container!=\"\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Memory Limits by Namespace",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", cluster=~\"${cluster}\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Load Per Node",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n  (avg by(check_ip) (label_replace(node_load1{cluster=~\"${cluster}\"}, \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\")) * (${operation} == bool 1))\n  +\n  (min by(check_ip) (label_replace(node_load1{cluster=~\"${cluster}\"}, \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\")) * (${operation} == bool 2))\n  +\n  (max by(check_ip) (label_replace(node_load1{cluster=~\"${cluster}\"}, \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\")) * (${operation} == bool 3))\n)\n/ on(check_ip)\ncount by(check_ip) (\n  group by(check_ip, cpu) (label_replace(node_cpu_seconds_total{mode=\"idle\", cluster=~\"${cluster}\"}, \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\"))\n)\n* on(check_ip) group_left(nodename) \navg by (check_ip, nodename) (label_replace(node_uname_info{nodename=~\"${node}\", cluster=~\"${cluster}\"}, \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\"))",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "Memory Load Per Node",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n  (avg by(check_ip) (label_replace(node_memory_MemTotal_bytes{cluster=~\"${cluster}\"} - node_memory_MemAvailable_bytes{cluster=~\"${cluster}\"}, \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\")) * (${operation} == bool 1))\n  +\n  (min by(check_ip) (label_replace(node_memory_MemTotal_bytes{cluster=~\"${cluster}\"} - node_memory_MemAvailable_bytes{cluster=~\"${cluster}\"}, \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\")) * (${operation} == bool 2))\n  +\n  (max by(check_ip) (label_replace(node_memory_MemTotal_bytes{cluster=~\"${cluster}\"} - node_memory_MemAvailable_bytes{cluster=~\"${cluster}\"}, \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\")) * (${operation} == bool 3))\n)\n/ on(check_ip)\nmax by(check_ip) (label_replace(node_memory_MemTotal_bytes{cluster=~\"${cluster}\"}, \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\"))\n* on(check_ip) group_left(nodename) \navg by (check_ip, nodename) (label_replace(node_uname_info{nodename=~\"${node}\", cluster=~\"${cluster}\"}, \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\"))",
       "legendFormat": "{{nodename}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage (Per Core)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (cpu, nodename) (label_replace(irate(node_cpu_seconds_total{mode!=\"idle\", cluster=~\"$cluster\"}[5m]), \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\") * on(check_ip) group_left(nodename) avg by (check_ip, nodename) (label_replace(node_uname_info{nodename=~\"$node\", cluster=~\"$cluster\"}, \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\"))) * 100",
       "legendFormat": "{{nodename}} - Core {{cpu}}"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace(node_load1{cluster=~\"$cluster\"}, \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\") * on(check_ip) group_left(nodename) avg by (check_ip, nodename) (label_replace(node_uname_info{nodename=~\"$node\", cluster=~\"$cluster\"}, \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\"))",
       "legendFormat": "{{nodename}} - 1m"
      },
      {
       "expr": "label_replace(node_load5{cluster=~\"$cluster\"}, \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\") * on(check_ip) group_left(nodename) avg by (check_ip, nodename) (label_replace(node_uname_info{nodename=~\"$node\", cluster=~\"$cluster\"}, \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\"))",
       "legendFormat": "{{nodename}} - 5m"
      },
      {
       "expr": "label_replace(node_load15{cluster=~\"$cluster\"}, \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\") * on(check_ip) group_left(nodename) avg by (check_ip, nodename) (label_replace(node_uname_info{nodename=~\"$node\", cluster=~\"$cluster\"}, \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\"))",
       "legendFormat": "{{nodename}} - 15m"
      }
     ]
    },
    {
     "title": "Memory Breakdown",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(node_memory_MemTotal_bytes{cluster=~\"$cluster\"} - node_memory_MemFree_bytes{cluster=~\"$cluster\"} - node_memory_Buffers_bytes{cluster=~\"$cluster\"} - node_memory_Cached_bytes{cluster=~\"$cluster\"}, \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\") * on(check_ip) group_left(nodename) avg by (check_ip, nodename) (label_replace(node_uname_info{nodename=~\"$node\", cluster=~\"$cluster\"}, \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\"))",
       "legendFormat": "{{nodename}} - Used"
      },
      {
       "expr": "label_replace(node_memory_Cached_bytes{cluster=~\"$cluster\"} + node_memory_Buffers_bytes{cluster=~\"$cluster\"}, \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\") * on(check_ip) group_left(nodename) avg by (check_ip, nodename) (label_replace(node_uname_info{nodename=~\"$node\", cluster=~\"$cluster\"}, \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\"))",
       "legendFormat": "{{nodename}} - Cached/Buffers"
      },
      {
       "expr": "label_replace(node_memory_MemFree_bytes{cluster=~\"$cluster\"}, \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\") * on(check_ip) group_left(nodename) avg by (check_ip, nodename) (label_replace(node_uname_info{nodename=~\"$node\", cluster=~\"$cluster\"}, \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\"))",
       "legendFormat": "{{nodename}} - Free"
      }
     ]
    },
    {
     "title": "Memory Usage Gauge",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - (label_replace(node_memory_MemAvailable_bytes{cluster=~\"$cluster\"} / node_memory_MemTotal_bytes{cluster=~\"$cluster\"}, \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\") * on(check_ip) group_left(nodename) avg by (check_ip, nodename) (label_replace(node_uname_info{nodename=~\"$node\", cluster=~\"$cluster\"}, \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\")) * 100)",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "Disk I/O",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "label_replace(rate(node_disk_read_bytes_total{device=~\"sd.*|vd.*|nvme.*\", cluster=~\"$cluster\"}[5m]), \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\") * on(check_ip) group_left(nodename) avg by (check_ip, nodename) (label_replace(node_uname_info{nodename=~\"$node\", cluster=~\"$cluster\"}, \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\"))",
       "legendFormat": "{{nodename}} - {{device}} Read"
      },
      {
       "expr": "label_replace(rate(node_disk_written_bytes_total{device=~\"sd.*|vd.*|nvme.*\", cluster=~\"$cluster\"}[5m]), \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\") * on(check_ip) group_left(nodename) avg by (check_ip, nodename) (label_replace(node_uname_info{nodename=~\"$node\", cluster=~\"$cluster\"}, \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\"))",
       "legendFormat": "{{nodename}} - {{device}} Write"
      }
     ]
    },
    {
     "title": "Disk Space Usage",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - (label_replace(node_filesystem_avail_bytes{fstype=~\"ext4|xfs|btrfs\", cluster=~\"$cluster\"} / node_filesystem_size_bytes{fstype=~\"ext4|xfs|btrfs\", cluster=~\"$cluster\"}, \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\") * on(check_ip) group_left(nodename) avg by (check_ip, nodename) (label_replace(node_uname_info{nodename=~\"$node\", cluster=~\"$cluster\"}, \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\")) * 100)",
       "legendFormat": "{{nodename}} - {{mountpoint}}"
      }
     ]
    },
    {
     "title": "Network Received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "label_replace(rate(node_network_receive_bytes_total{device!~\"lo|veth.*|cali.*|flannel.*\", cluster=~\"$cluster\"}[5m]), \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\") * on(check_ip) group_left(nodename) avg by (check_ip, nodename) (label_replace(node_uname_info{nodename=~\"$node\", cluster=~\"$cluster\"}, \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\"))",
       "legendFormat": "{{nodename}} - {{device}}"
      }
     ]
    },
    {
     "title": "Network Transmitted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "label_replace(rate(node_network_transmit_bytes_total{device!~\"lo|veth.*|cali.*|flannel.*\", cluster=~\"$cluster\"}[5m]), \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\") * on(check_ip) group_left(nodename) avg by (check_ip, nodename) (label_replace(node_uname_info{nodename=~\"$node\", cluster=~\"$cluster\"}, \"check_ip\", \"$1\", \"instance\", \"(.*?)(:.*)?\"))",
       "legendFormat": "{{nodename}} - {{device}}"
      }
     ]
    }
   ]
  }
 ]
}