# kubectl create secret generic bw-auth-token -n sm-operator-system --from-literal=token="TOKEN" --dry-run=client -o yaml | kubectl annotate --local -f - reflector.v1.k8s.emberstack.com/reflection-allowed=true reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces=.* reflector.v1.k8s.emberstack.com/reflection-auto-enabled=true -o yaml | kubectl apply -f -
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: bitwarden-secretsmanager
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      auth:
        secretRef:
          credentials:
            key: token
            name: bw-auth-token
      bitwardenServerSDKURL: https://bitwarden-sdk-server.default.svc.cluster.local:9998
      organizationID: "1a1f473f-c6a3-47af-a106-b29800f5ca1f"
