apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: it-tools
  namespace: it-tools
spec:
  scaleTargetRef:
    name: it-tools
  minReplicaCount: 0
  maxReplicaCount: 1
  cooldownPeriod: 300
  triggers:
    - type: cron
      metadata:
        timezone: Europe/Oslo
        start: "0 7 * * *"
        end: "0 23 * * *"
        desiredReplicas: "1"
