apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: semaphore-admin-secret
  namespace: semaphore
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: semaphore-admin-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: "f812d767-73ce-4fbe-81e9-b2ee00f8f2f6"
    - secretKey: password
      remoteRef:
        key: "4bafed2a-ee0d-45d6-8c17-b2ee00f9259c"
    - secretKey: email
      remoteRef:
        key: "b4c58fa0-5efa-40c3-9ad0-b2ee00f96b88"
    - secretKey: fullname
      remoteRef:
        key: "9791d4b6-e495-4238-a01b-b2ee00f9a6e2"
