---
- tags: bind_config
  block:
    - name: Deploy named.conf.options
      ansible.builtin.template:
        src: named.conf.options.j2
        dest: /etc/bind/named.conf.options
        owner: root
        group: bind
        mode: '0644'
      notify: Restart bind9

    - name: Deploy named.conf.local
      ansible.builtin.template:
        src: named.conf.local.j2
        dest: /etc/bind/named.conf.local
        owner: root
        group: bind
        mode: '0644'
      notify: Restart bind9
