---
- block:
    - name: install BIND9 packages
      ansible.builtin.package:
        name: "{{ bind_zone_manager_packages }}"
        state: latest

    - name: ensure bind9 is enabled & running
      ansible.builtin.systemd:
        name: bind9
        enabled: true
        state: started
  tags: bind_install
