apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc
  namespace: argo-cd
spec:
  project: homelab
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-systems
  sources:
    - repoURL: "https://github.com/mortennordbye/Homelab.git"
      targetRevision: main
      path: clusters/k3sa/helm-charts/gha-runner-wrapper
      helm:
        valueFiles:
          - values.yaml
    - repoURL: "https://github.com/mortennordbye/Homelab.git"
      targetRevision: main
      ref: values
      path: clusters/k3sa/manifests/arc
      directory:
        recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true