apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc
  namespace: argo-cd
spec:
  project: homelab
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-systems
  sources:
    - repoURL: "https://actions-runner-controller.github.io/actions-runner-controller"
      chart: actions-runner-controller
      targetRevision: "0.23.7"
      helm:
        valueFiles:
          - $values/k8s/clusters/k3sa/helm-values/arc-values.yaml
    - repoURL: "https://github.com/mortennordbye/Homelab.git"
      targetRevision: main
      ref: values
      path: k8s/clusters/k3sa/manifests/arc
      directory:
        recurse: true

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
