apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo-cd
spec:
  project: homelab
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  sources:
    - repoURL: "https://argoproj.github.io/argo-helm"
      chart: argo-cd
      targetRevision: "8.0.10"
      helm:
        valueFiles:
          - $values/k8s/clusters/k3sa/helm-values/argo-cd-values.yaml
    - repoURL: "https://github.com/mortennordbye/Homelab.git"
      targetRevision: main
      ref: values
      path: k8s/clusters/k3sa/manifests/argo-cd
      directory:
        recurse: true
         
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
