apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: it-tools
  namespace: argo-cd
spec:
  project: homelab
  destination:
    server: https://kubernetes.default.svc
    namespace: it-tools
  source:
    repoURL: https://github.com/mortennordbye/Homelab.git
    targetRevision: main
    path: k8s/clusters/k3sa/manifests/it-tools
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
# Test
