apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: semaphore
  namespace: argo-cd
spec:
  project: homelab
  destination:
    server: https://kubernetes.default.svc
    namespace: semaphore
  sources:
    - repoURL: "https://semaphoreui.github.io/charts/"
      chart: semaphore
      targetRevision: "16.0.0"
      helm:
        valueFiles:
          - $values/k8s/clusters/k3sa/helm-values/semaphore-values.yaml
    - repoURL: "https://github.com/mortennordbye/Homelab.git"
      targetRevision: main
      ref: values
      path: k8s/clusters/k3sa/manifests/semaphore
      directory:
        recurse: true

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
