apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sm-operator
  namespace: argo-cd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  sources:
    - repoURL: "https://charts.bitwarden.com/"
      chart: sm-operator
      targetRevision: "0.1.0-Beta"
      helm:
        valueFiles:
          - $values/k8s/clusters/k3sa/helm-values/sm-operator-values.yaml
    - repoURL: "https://github.com/mortennordbye/Homelab.git"
      targetRevision: main
      ref: values
      path: k8s/clusters/k3sa/manifests/sm-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
