apiVersion: v1
kind: Service
metadata:
  name: proxmox-service
  namespace: traefik
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8006
      targetPort: 8006
---
apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox-service
  namespace: traefik
subsets:
  - addresses:
      - ip: 10.0.0.4
    ports:
      - name: http
        port: 8006
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: proxmox-ingress
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`hyper1.local.bigd.no`)
      kind: Rule
      middlewares:
        - name: default-headers
          namespace: traefik
      services:
        - name: proxmox-service
          port: 8006
  tls:
    secretName: local-bigd-no-tls
