apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homarr-db-encryption-secret
  namespace: homarr
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: homarr-db-secret
    creationPolicy: Owner
  data:
    - secretKey: db-encryption-key
      remoteRef:
        key: "61de5f38-f6fd-4d67-8ca7-b2c8012843ef"
