replicaCount: 1
strategyType: RollingUpdate

env:
  TZ: "Europe/Oslo"

envSecrets:
  dbCredentials:
    existingSecret: homarr-db-secret
    dbEncryptionKey: db-encryption-key

persistence:
  homarrDatabase:
    enabled: true
    storageClassName: syno-nfs
    size: "1Gi"

rbac:
  enabled: true

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: traefik-default-headers@kubernetescrd
  hosts:
    - host: hub.bigd.no
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - hub.bigd.no
      secretName: bigd-no-tls
