apiVersion: v1
kind: Service
metadata:
  name: hub-service
  namespace: traefik
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 7575
---
apiVersion: v1
kind: Endpoints
metadata:
  name: hub-service
  namespace: traefik
subsets:
  - addresses:
      - ip: 10.0.0.27
    ports:
      - name: http
        port: 7575
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hub-ingress
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`hub.bigd.no`)
      kind: Rule
      middlewares:
        - name: default-headers
          namespace: traefik
      services:
        - name: hub-service
          port: 80
  tls:
    secretName: bigd-no-tls