apiVersion: v1
kind: Service
metadata:
  name: registry-gitlab-service
  namespace: traefik
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 5050
      targetPort: 5050
---
apiVersion: v1
kind: Endpoints
metadata:
  name: registry-gitlab-service
  namespace: traefik
subsets:
  - addresses:
      - ip: 10.0.0.36
    ports:
      - name: http
        port: 5050
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: registry-gitlab-ingress
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`registry.gitlab.bigd.no`)
      kind: Rule
      middlewares:
        - name: default-headers
          namespace: traefik
      services:
        - name: registry-gitlab-service
          port: 5050
  tls:
    secretName: bigd-no-tls
