baseURL = "https://blog.nordbye.it/"
languageCode = "en-us"
title = "Morten Victor Nordbye"
theme = "hextra"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
noClasses = false

[[menu.main]]
identifier = "documentation"
name = "Documentation"
pageRef = "/docs"
weight = 1

[[menu.main]]
identifier = "blog"
name = "Blog"
pageRef = "/blog"
weight = 2

[[menu.main]]
identifier = "about"
name = "About"
pageRef = "/about"
weight = 3

[params]
description = "Infrastructure notes and Kubernetes experiments"

[params.footer]
displayCopyright = true
displayPoweredBy = false

[params.theme]
default = "system"
displayToggle = true

[params.comments]
enable = true
type = "giscus"

[params.comments.giscus]
repo = "mortennordbye/homelab"
repoId = "R_kgDOOEXL5g"
category = "Announcements"
categoryId = "DIC_kwDOOEXL5s4C06qE"

[params.search]
enable = true
type = "flexsearch"
[params.navbar]
displayTitle = true
displayLogo = true
[params.navbar.logo]
path = "images/profile.png"
width = 40
height = 40

[params.blog]
[params.blog.list]
displayTags = true

[[params.navbar.customLinks]]
name = "GitHub"
url = "https://github.com/mortennordbye"

[[params.navbar.customLinks]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/morten-nordbye-325bb71bb"
