# The SNMPv3 user on the NAS (DSM > Terminal & SNMP) must match: snmp-exporter,
# SHA auth, AES privacy.
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: snmp-exporter-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: snmp-exporter-auth
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        auth.yml: |
          auths:
            synology_v3:
              version: 3
              security_level: authPriv
              username: snmp-exporter
              auth_protocol: SHA
              password: "{{ .auth }}"
              priv_protocol: AES
              priv_password: "{{ .priv }}"
  data:
    - secretKey: auth
      remoteRef:
        key: "8c614867-d0e5-4f3a-89db-b4d1013f30b1"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: priv
      remoteRef:
        key: "913bdb59-2d64-4cc1-a546-b4d1013f3134"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
