services:
  nginx-proxy:
    container_name: nginx_proxy
    image: ${NPM_IMAGE}
    restart: unless-stopped
    ports:
      - "180:80"
      - "181:81"
      - "1443:443"
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt

volumes:
  data:
  letsencrypt:
