apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: bw-sample-secret
  namespace: kube-system  # Move to target namespace
spec:
  organizationId: "1a1f473f-c6a3-47af-a106-b29800f5ca1f"
  secretName: "ping"
  map:
    - bwSecretId: "d5671d8a-a9d1-472e-ab0b-b29b00d1915b"
      secretKeyName: "ping"
  authToken:
    secretName: bw-auth-token
    secretKey: token
