gha-runner-scale-set-controller:
  authSecret:
    enabled: true
    create: false
    name: arc-github-token

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
