all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    homelab:
      hosts:
        unifi-network.local.bigd.no:
        adguard.local.bigd.no:
        bind.local.bigd.no:
        linbast.local.bigd.no:
        docker-alfa.local.bigd.no:
        docker-piracy.local.bigd.no:
        qbittorrent.local.bigd.no:
        plex.local.bigd.no:
        gitlab.local.bigd.no:
        k3sam1.local.bigd.no:
        k3sam2.local.bigd.no:
        k3sam3.local.bigd.no:
        k3saca1.local.bigd.no:
        k3saca2.local.bigd.no:
        k3saca3.local.bigd.no:
        test-ansible.local.bigd.no:
