---
- name: Initial setup of Ansible user
  hosts: all
  become: yes
  gather_facts: no
  collections:
    - ansible.builtin
    - ansible.posix

  tasks:
    - name: Ensure Ansible user exists
      ansible.builtin.user:
        name: ansibleadmin
        state: present
        create_home: yes
        shell: /bin/bash

    - name: Set up authorized SSH keys for the Ansible user
      ansible.posix.authorized_key:
        user: ansibleadmin
        state: present
        key: "{{ lookup('ansible.builtin.file', 'files/ansible_user.pub') }}"

    - name: Copy sudoers file for the Ansible user
      ansible.builtin.copy:
        src: files/ansible_user_sudo
        dest: /etc/sudoers.d/ansibleadmin
        owner: root
        group: root
        mode: '0440'
        validate: '/usr/sbin/visudo -cf %s'
