apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingressroute.yaml

namespace: monitoring

helmCharts:
  - name: loki
    repo: https://grafana.github.io/helm-charts
    includeCRDs: true
    namespace: monitoring
    version: "6.37.0"
    releaseName: loki
    valuesFile: ./values.yaml
