# Loki for homelab without object storage
deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi
  persistence:
    enabled: true
    size: 20Gi
    storageClass: syno-nfs

memcached:
  enabled: false

read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0

loki:
  auth_enabled: false
  useTestSchema: true
  commonConfig:
    path_prefix: /var/loki
    replication_factor: 1
  limits_config:
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    max_cache_freshness_per_query: 10m
    query_timeout: 60s
    split_queries_by_interval: 15m
    volume_enabled: true
  ui:
    enabled: true

  storage:
    type: filesystem
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules
ingress:
  enabled: true
  ingressClassName: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
  hosts:
    - loki.local.bigd.no
  tls:
    - hosts:
        - loki.local.bigd.no
      secretName: local-bigd-tls
  paths:
    distributor:
      - /api/prom/push
      - /loki/api/v1/push
      - /otlp/v1/logs
      - /ui
    queryFrontend:
      - /api/prom/query
      - /api/prom/label
      - /api/prom/series
      - /api/prom/tail
      - /loki/api/v1/query
      - /loki/api/v1/query_range
      - /loki/api/v1/tail
      - /loki/api/v1/label
      - /loki/api/v1/labels
      - /loki/api/v1/series
      - /loki/api/v1/index/stats
      - /loki/api/v1/index/volume
      - /loki/api/v1/index/volume_range
      - /loki/api/v1/format_query
      - /loki/api/v1/detected_field
      - /loki/api/v1/detected_fields
      - /loki/api/v1/detected_labels
      - /loki/api/v1/patterns
    ruler:
      - /api/prom/rules
      - /api/prom/api/v1/rules
      - /api/prom/api/v1/alerts
      - /loki/api/v1/rules
      - /prometheus/api/v1/rules
      - /prometheus/api/v1/alerts
    compactor:
      - /loki/api/v1/delete
gateway:
  enabled: true
  service:
    type: ClusterIP
    port: 80
  basicAuth:
    enabled: false

lokiCanary:
  enabled: false
test:
  enabled: false
