# Loki for homelab without object storage
deploymentMode: SingleBinary

loki:
  auth_enabled: false
  useTestSchema: true
  commonConfig:
    path_prefix: /var/loki
    replication_factor: 1
  limits_config:
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    max_cache_freshness_per_query: 10m
    query_timeout: 60s
    split_queries_by_interval: 15m
    volume_enabled: true
  ui:
    enabled: true
  storage:
    type: filesystem
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules

singleBinary:
  persistence:
    enabled: true
    size: 20Gi
    storageClass: syno-nfs

gateway:
  enabled: true
  service:
    type: ClusterIP
    port: 80
  basicAuth:
    enabled: false

lokiCanary:
  enabled: false
test:
  enabled: false
