apiVersion: apps/v1
kind: Deployment
metadata:
  name: omni-tools
  namespace: omni-tools
  labels:
    app: omni-tools
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: omni-tools
  template:
    metadata:
      labels:
        app: omni-tools
    spec:
      containers:
        - name: omni-tools
          image: iib0011/omni-tools:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources: {}
