apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: discord-alerts
  namespace: kube-prometheus-stack
spec:
  route:
    receiver: discord
    groupBy: ['alertname', 'namespace']
    continue: false
    routes:
      - matchers:
          - name: alertname
            matchType: "=~"
            value: "DiskUsageCritical|DiskUsageWarning"
  receivers:
    - name: discord
      webhookConfigs:
        - urlSecret:
            name: alertmanager-discord-webhook-secret
            key: api-url
          sendResolved: true
          maxAlerts: 5
