apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: kube-prometheus-stack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: grafana-admin-credentials
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: "51d9081d-d76c-4a7a-a6c7-b2a201221564"
    - secretKey: admin-password
      remoteRef:
        key: "c964dc2b-f954-47da-aa38-b2a2012270fe"


