# Password of the local UniFi user unpoller, Network role View Only.
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unpoller
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: unpoller
    creationPolicy: Owner
  data:
    - secretKey: UP_UNIFI_DEFAULT_PASS
      remoteRef:
        key: "fab08089-bbe4-4021-9064-b4d10150b5bb"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
