apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: blog-policy
  namespace: blog
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: blog
  ingress:
    - fromEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": traefik
            "k8s:app.kubernetes.io/instance": traefik-traefik
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
    - fromEntities:
        - host
        - health
