apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - prod/deployment.yaml
  - prod/ingressroute.yaml
  - prod/service.yaml
  - stage/deployment.yaml
  - stage/ingressroute.yaml
  - stage/service.yaml