global:
  domain: argocd.local.bigd.no

crds:
  install: true

configs:
  params:
    server.insecure: true
  cm:
    kustomize.buildOptions: "--enable-helm"
    exec.enabled: "true"

server:
  replicas: 1
  service:
    type: LoadBalancer
    annotations:
      lbipam.cilium.io/ips: "10.3.10.100"
  ingress:
    enabled: false
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack

dex:
  enabled: false

notifications:
  enabled: true

applicationSet:
  enabled: true

redis-ha:
  enabled: false

controller:
  replicas: 1
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack

repoServer:
  replicas: 1
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack