apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - project.yaml
  - projectconfig.yaml
  - git-credentials.yaml
  - warehouse.yaml
  - analysistemplate.yaml
  - stage-stage.yaml
  - stage-prod.yaml
