apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: portfolio-stage-policy
  namespace: stage-portfolio
spec:
  endpointSelector:
    matchLabels:
      app: stage-portfolio
  ingress:
    - fromEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": traefik
            "k8s:app.kubernetes.io/instance": traefik-traefik
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
    - fromEntities:
        - host
        - health
