apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-stage
  namespace: stage-portfolio
  labels:
    app: stage-portfolio
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: stage-portfolio
  template:
    metadata:
      labels:
        app: stage-portfolio
    spec:
      terminationGracePeriodSeconds: 15
      automountServiceAccountToken: false
      hostNetwork: false
      hostPID: false
      hostIPC: false
      enableServiceLinks: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
        runAsUser: 101     # nginx user in official nginx:alpine
        runAsGroup: 101
      containers:
        - name: portfolio
          image: ghcr.io/mortennordbye/portfolio:stage
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            privileged: false
            runAsNonRoot: true
            runAsUser: 101
            runAsGroup: 101
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
              httpHeaders:
                - name: Host
                  value: stage.nordbye.it
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
              httpHeaders:
                - name: Host
                  value: stage.nordbye.it
            initialDelaySeconds: 5
            periodSeconds: 15
            failureThreshold: 3
