apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-stage
  namespace: stage-portfolio
  labels:
    app: stage-portfolio
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: stage-portfolio
  template:
    metadata:
      labels:
        app: stage-portfolio
    spec:
      containers:
        - name: portfolio
          image: ghcr.io/mortennordbye/portfolio:stage
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
            - name: tmp
              mountPath: /tmp
          resources: {}
      volumes:
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
        - name: tmp
          emptyDir: {}
