apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - project-homelab.yaml

namespace: argo-cd

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    includeCRDs: true
    namespace: argo-cd
    version: 8.1.3
    releaseName: argo-cd
    valuesFile: ./values.yaml