apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: semaphore-db-secret
  namespace: semaphore
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: semaphore-db-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: "b14eb7d2-4073-4f52-88c1-b2ee00f9d261"
    - secretKey: password
      remoteRef:
        key: "0c0090a5-f18e-4301-b484-b2ee00fa100f"
