apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  namespace: argo-cd
spec:
  project: app-of-apps
  source:
    path: k8s/k3sa/apps
    repoURL: https://github.com/mortennordbye/Homelab.git
    targetRevision: HEAD
  destination:
    namespace: argo-cd
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 1
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
