apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/external-secrets/external-secrets/v0.17.0/deploy/crds/bundle.yaml # renovate: https://charts.external-secrets.io
- https://github.com/cert-manager/cert-manager/releases/download/v1.18.2/cert-manager.crds.yaml # renovate: https://charts.jetstack.io