apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gatus-discord-webhook-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: gatus-discord-webhook-secret
    creationPolicy: Owner
  data:
    - secretKey: DISCORD_WEBHOOK_URL
      remoteRef:
        key: "1c16150b-bfc8-4064-ad65-b2a201197373"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: TRAEFIK_BASIC_AUTH
      remoteRef:
        key: "c896213c-3dce-40d7-85dc-b2a2011e133f"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
