apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gatus-discord-webhook-ext-secret.yaml
  - ingressroute.yaml
  - namespace.yaml
  
namespace: monitoring

helmCharts:
  - name: gatus
    repo: https://twin.github.io/helm-charts
    includeCRDs: true
    namespace: monitoring
    version: 1.4.0
    releaseName: gatus
    valuesFile: ./values.yaml