env:
  - name: GATUS_WATCH_CONFIG
    value: "false"

deployment:
  strategy: Recreate
  annotateConfigChecksum: true
  revisionHistoryLimit: 2

persistence:
  enabled: true
  size: 1Gi
  mountPath: /data
  storageClassName: syno-nfs
  accessModes:
    - ReadWriteOnce


ingress:
  enabled: false

service:
  type: ClusterIP
  port: 80

securityContext:
  runAsNonRoot: true
  runAsUser: 65534
  runAsGroup: 65534
  readOnlyRootFilesystem: true

readinessProbe:
  enabled: true
livenessProbe:
  enabled: true

resources: {}

serviceMonitor:
  enabled: false

networkPolicy:
  enabled: false

envFrom:
  - secretRef:
      name: gatus-discord-webhook-secret

config:
  alerting:
    discord:
      webhook-url: "${DISCORD_WEBHOOK_URL}"
      default-alert:
        description: "@everyone Health Check Update"
        send-on-resolved: true
        failure-threshold: 2
        success-threshold: 2

  maintenance:
    enabled: false
    start: "23:00"
    duration: "1h"
    timezone: "Europe/Oslo"
  storage:
    type: sqlite
    path: /data/data.db


  internal-http-defaults: &internal-http-defaults
    group: Internal HTTP
    method: GET
    interval: 15s
    client:
      timeout: 10s
    conditions:
      - "[STATUS] < 302"
    alerts:
      - type: discord

  external-http-defaults: &external-http-defaults
    group: External HTTP
    method: GET
    interval: 15s
    client:
      timeout: 10s
    conditions:
      - "[STATUS] < 302"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: discord

  internal-tcp-ssh-defaults: &internal-tcp-ssh-defaults
    group: Internal TCP SSH
    interval: 30s
    client:
      timeout: 10s
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord

  internal-tcp-rdp-defaults: &internal-tcp-rdp-defaults
    group: Internal TCP RDP
    interval: 30s
    client:
      timeout: 10s
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord

  endpoints:
    ## Internal HTTP (IP-based)
    - name: pfSense
      <<: *internal-http-defaults
      url: "https://10.0.0.1"

    - name: Synology
      <<: *internal-http-defaults
      url: "https://10.0.0.2:5001"

    - name: Proxmox
      <<: *internal-http-defaults
      url: "https://10.0.0.4:8006/#"

    - name: ILO
      <<: *internal-http-defaults
      url: "https://10.0.0.5"

    - name: AdGuard Home
      <<: *internal-http-defaults
      url: "http://10.0.0.21"

    - name: Argo-cd
      <<: *internal-http-defaults
      url: "https://10.0.0.59"

    - name: Nginx Proxy Manager
      <<: *internal-http-defaults
      url: "http://10.0.0.27:181"

    - name: Portainer
      <<: *internal-http-defaults
      url: "https://10.0.0.27:9443"

    - name: Your Spotify
      <<: *internal-http-defaults
      url: "http://10.0.0.27:3000/"

    - name: pgAdmin-4
      <<: *internal-http-defaults
      url: "http://10.0.0.27:37492/login?next=/browser/"

    - name: Sonarr
      <<: *internal-http-defaults
      url: "http://10.0.0.27:8989"

    - name: Radarr
      <<: *internal-http-defaults
      url: "http://10.0.0.27:7878"

    - name: Readarr
      <<: *internal-http-defaults
      url: "http://10.0.0.27:8787"

    - name: Bazarr
      <<: *internal-http-defaults
      url: "http://10.0.0.27:6767"

    - name: Prowlarr
      <<: *internal-http-defaults
      url: "http://10.0.0.27:9696"

    - name: Tdarr
      <<: *internal-http-defaults
      url: "http://10.0.0.27:8265"

    - name: FlareSolverr
      <<: *internal-http-defaults
      url: "http://10.0.0.27:8191"

    - name: qBittorrent
      <<: *internal-http-defaults
      url: "http://10.0.0.27:8080"

    - name: yt-dlp-web
      <<: *internal-http-defaults
      url: "http://10.0.0.27:3033"

    - name: Huntarr
      <<: *internal-http-defaults
      url: "http://10.0.0.27:9705"

    - name: Plex (Internal)
      <<: *internal-http-defaults
      url: "http://10.0.0.28:32400/web"

    - name: Tautulli
      <<: *internal-http-defaults
      url: "http://10.0.0.28:8181"

    - name: Home Assistant
      <<: *internal-http-defaults
      url: "http://10.0.0.30:8123"

    - name: PBS
      <<: *internal-http-defaults
      url: "https://10.0.0.23:8007"

    - name: UniFi-Network
      <<: *internal-http-defaults
      url: "https://10.0.0.10:8443"

    ## Internal HTTP (FQDN-based)
    - name: Traefik
      <<: *internal-http-defaults
      url: "https://traefik.local.bigd.no/dashboard/#"
      headers:
        Authorization: "Basic ${TRAEFIK_BASIC_AUTH}"

    - name: Gatus
      <<: *internal-http-defaults
      url: "https://uptime.local.bigd.no/"

    - name: Prometheus
      <<: *internal-http-defaults
      url: "https://prometheus.local.bigd.no/query"

    - name: Grafana
      <<: *internal-http-defaults
      url: "https://grafana.local.bigd.no/"

    - name: Argo-cd-FQDN
      <<: *internal-http-defaults
      url: "https://argocd.local.bigd.no"

    ## External HTTP (FQDN-based)
    - name: Plex
      <<: *external-http-defaults
      url: "https://app.plex.tv"

    - name: Overseerr
      <<: *external-http-defaults
      url: "https://overseerr.bigd.no"

    - name: Prod-Portfolio
      <<: *external-http-defaults
      url: "https://nordbye.it/"

    - name: Stage-Portfolio
      <<: *external-http-defaults
      url: "https://stage.nordbye.it/"

    - name: Audiobookshelf
      <<: *external-http-defaults
      url: "https://audiobookshelf.bigd.no"

    - name: OmniTools
      <<: *external-http-defaults
      url: "https://omni-tools.bigd.no/"

    - name: It-Tools
      <<: *external-http-defaults
      url: "https://it-tools.bigd.no/"

    - name: Homarr
      <<: *external-http-defaults
      url: "https://hub.bigd.no/"
        
    ## Internal TCP SSH (FQDN-based)
    - name: pfSense
      <<: *internal-tcp-ssh-defaults
      url: "tcp://pfSense.local.bigd.no:22"

    - name: NAS - Synology LAN1
      <<: *internal-tcp-ssh-defaults
      url: "tcp://nas1.local.bigd.no:22"

    - name: Hyper1(ProLiant DL380 Gen10)
      <<: *internal-tcp-ssh-defaults
      url: "tcp://hyper1.local.bigd.no:22"

    - name: Hyper1(ProLiant DL380 Gen10)(ILO)
      <<: *internal-tcp-ssh-defaults
      url: "tcp://hyper1ilo.local.bigd.no:22"

    - name: Linbast
      <<: *internal-tcp-ssh-defaults
      url: "tcp://linbast.local.bigd.no:22"

    - name: Docker-Piracy
      <<: *internal-tcp-ssh-defaults
      url: "tcp://servarr.local.bigd.no:22"

    - name: Plex
      <<: *internal-tcp-ssh-defaults
      url: "tcp://plex.local.bigd.no:22"

    - name: Homeassistant
      <<: *internal-tcp-ssh-defaults
      url: "tcp://homeassistant.local.bigd.no:22"

    - name: k3sam1
      <<: *internal-tcp-ssh-defaults
      url: "tcp://k3sam1.local.bigd.no:22"

    - name: k3sam2
      <<: *internal-tcp-ssh-defaults
      url: "tcp://k3sam2.local.bigd.no:22"

    - name: k3sam3
      <<: *internal-tcp-ssh-defaults
      url: "tcp://k3sam3.local.bigd.no:22"

    - name: k3saca1
      <<: *internal-tcp-ssh-defaults
      url: "tcp://k3saca1.local.bigd.no:22"

    - name: k3saca2
      <<: *internal-tcp-ssh-defaults
      url: "tcp://k3saca2.local.bigd.no:22"

    - name: k3saca3
      <<: *internal-tcp-ssh-defaults
      url: "tcp://k3saca3.local.bigd.no:22"

    ## Internal TCP SSH (IP-based)
    - name: Adguard
      <<: *internal-tcp-ssh-defaults
      url: "tcp://10.0.0.21:22"

    - name: BIND
      <<: *internal-tcp-ssh-defaults
      url: "tcp://10.0.0.22:22"

    ## Internal TCP RDP (FQDN)
    - name: Gaming PC
      <<: *internal-tcp-rdp-defaults
      url: "tcp://gaming.local.bigd.no:3389"
      enabled: false
