replicaCount: 1

ingress:
  enabled: true
  className: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: traefik-default-headers@kubernetescrd
  hosts:
    - host: semaphore.local.bigd.no
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - semaphore.local.bigd.no
      secretName: local-bigd-tls

persistence:
  enabled: true
  size: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClass: syno-nfs

database:
  type: postgres
  host: docker-alfa.local.bigd.no
  port: 5432
  name: semaphore
  existingSecret: semaphore-db-secret
  usernameKey: username
  passwordKey: password
  usernameFromSecret: true

extraEnvVariables:
  SEMAPHORE_DB_OPTIONS: '{"sslmode":"disable"}'

admin:
  create: true
  existingSecret: semaphore-admin-secret
  usernameKey: username
  passwordKey: password
  emailKey: email
  fullnameKey: fullname