# kubectl create secret generic bw-auth-token -n sm-operator-system --from-literal=token="TOKEN" --dry-run=client -o yaml | kubectl annotate --local -f - reflector.v1.k8s.emberstack.com/reflection-allowed=true reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces=.* reflector.v1.k8s.emberstack.com/reflection-auto-enabled=true -o yaml | kubectl apply -f -
settings:
  bwSecretsManagerRefreshInterval: 300
  cloudRegion: US
  replicas: 1
containers:
  manager:
    image:
      repository: ghcr.io/bitwarden/sm-operator
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  kubeRbacProxy:
    image:
      repository: gcr.io/kubebuilder/kube-rbac-proxy
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 5m
        memory: 64Mi
  serviceAccount:
    annotations: {}
  enableSeccompProfileRuntimeDefault: true
metricsService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  type: ClusterIP
