globalArguments:
  - "--global.sendanonymoususage=false"
  - "--global.checknewversion=false"
additionalArguments:
  - "--entryPoints.web.address=:80"
  - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
  - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
  - "--entryPoints.web.http.redirections.entryPoint.priority=10"
  - "--entryPoints.websecure.address=:443"
  - "--entryPoints.websecure.http3.enabled=true"
  - "--entryPoints.ssh.address=:2222"
  - "--entryPoints.metrics.address=:8082"

deployment:
  enabled: true
  replicas: 3

ports:
  web:
    exposedPort: 80
  websecure:
    exposedPort: 443
  ssh:
    port: 2222
    expose:
      default: true
    exposedPort: 2222
    protocol: TCP

logs:
  general:
    level: INFO

http:
  serversTransports:
    default:
      insecureSkipVerify: true

providers:
  kubernetesCRD:
    enabled: true
    ingressClass: traefik
    allowExternalNameServices: true
    allowCrossNamespace: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    publishedService:
      pathOverride: traefik/traefik

service:
  enabled: true
  type: LoadBalancer
  spec:
    loadBalancerIP: 10.0.0.58

metrics:
  prometheus:
    serviceMonitor:
      enabled: true
      namespace: monitoring
      namespaceSelector:
        matchNames:
          - traefik
      additionalLabels:
        Release: kube-prometheus-stack
      interval: 30s
      scrapeTimeout: 10s
