name: "Server Update Reminder (≈30 days)"

on:
  workflow_dispatch:
  schedule:
    # 16:00 UTC on the 15th of each month ≃ 18:00 Europe/Oslo
    - cron: '0 16 15 * *'

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Get Discord Webhook URL from Bitwarden
        id: bw-fetch
        uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BW_ACCESS_TOKEN }}
          secrets: |
            ab7c03b3-dc21-4174-babf-b2cf00f9ae40 > HOMELAB_SERVER_UPDATES_WEBHOOK_URL

      - name: Send Discord reminder
        run: |
          now=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          curl -sSL -H "Content-Type: application/json" -X POST \
               -d '{
                 "username": "Homelab-Reminders",
                 "embeds":[
                   {
                     "title":"🔔 Server Update Reminder",
                     "description":"An alert for Server Updates has been triggered.",
                     "color":16711680,
                     "fields":[
                       {
                         "name":"📌 @everyone",
                         "value":"• 🔄 Update servers"
                       },
                       {
                         "name":"⏳ Next run",
                         "value":"Every 15th of the month at 18:00 Oslo time"
                       }
                     ],
                     "footer":{"text":"Automated Reminder • Homelab"},
                     "timestamp":"'"$now"'"
                   }
                 ]
               }' \
               "$HOMELAB_SERVER_UPDATES_WEBHOOK_URL"
