name: "Kubernetes Update Reminder (≈30 days)"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 1 * *'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Get Discord Webhook URL from Bitwarden
        id: bw-fetch
        uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BW_ACCESS_TOKEN }}
          secrets: |
            ab7c03b3-dc21-4174-babf-b2cf00f9ae40 > HOMELAB_REMINDERS_WEBHOOK_URL

      - name: Send Discord reminder
        run: |
          now=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          curl -sSL -H "Content-Type: application/json" -X POST \
               -d '{
                 "username": "Homelab-Reminders",
                 "embeds":[
                   {
                     "title":"🔔 Kubernetes Update Reminder",
                     "description":"An alert for Kubernetes upkeep has been triggered.",
                     "color":15548997,
                     "fields":[
                       {
                         "name":"📌 @everyone",
                         "value":"• 🔄 CRDs: check & apply updates\n• 🤖 Renovate: review & merge PRs"
                       },
                       {
                         "name":"⏳ Next run",
                         "value":"Every 1st of the month at 18:00 Oslo time"
                       }
                     ],
                     "footer":{"text":"Automated Reminder • Homelab"},
                     "timestamp":"'"$now"'"
                   }
                 ]
               }' \
               "$HOMELAB_REMINDERS_WEBHOOK_URL"
