name: Deploy Argo configs

on:
  push:
    paths:
      - 'k8s/argo/**'
  workflow_dispatch:

jobs:
  apply-argo:
    runs-on: arc-runner-set

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.HOMELAB_K3SA_KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Apply all Argo manifests
        run: kubectl apply -R -f k8s/argo/
