name: Deploy Argo configs

on:
  push:
    paths:
      - 'k8s/argo/**'
  workflow_dispatch:

jobs:
  apply-argo:
    runs-on: arc-runner-set

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Get Kubeconfig from Bitwarden
        id: bw-kube
        uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BW_ACCESS_TOKEN }}
          secrets: |
            ab7c03b3-dc21-4174-babf-b2cf00f9ae40 > HOMELAB_K3SA_KUBECONFIG

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          printf '%b' "$HOMELAB_K3SA_KUBECONFIG" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Apply only changed Argo manifests
        run: |
          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- k8s/argo)
          if [ -z "$CHANGED" ]; then
            echo "✅ No changes in k8s/argo → skipping apply"
            exit 0
          fi
          echo "🔍 Changed files:"
          echo "$CHANGED"
          echo "$CHANGED" | xargs -r -n1 kubectl apply -f
