apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: gastam
  namespace: gastam
spec:
  target:
    service: gastam-service
    port: 80
  rules:
    - hosts:
        - gastam.bigd.no
  scalingMetric:
    concurrency:
      targetValue: 100
