apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: gastam-site
    namespace: gastam
    files:
      - index.html

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - ciliumnetworkpolicy.yaml
  - interceptorroute.yaml
  - scaledobject.yaml
