apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap.yaml
- deployment.yaml
- ingressroute.yaml
- namespace.yaml
- owncloud-ext-secret.yaml
- persistentvolumeclaim.yaml
- service.yaml