apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: owncloud-secrets
  namespace: owncloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: owncloud-secrets
    creationPolicy: Owner
  data:
    - secretKey: OWNCLOUD_DB_USERNAME
      remoteRef:
        key: "87d56296-8e21-4cbc-b16c-b2da00f7c869"
    - secretKey: OWNCLOUD_DB_PASSWORD
      remoteRef:
        key: "73cf3b02-847d-42c9-bdfc-b2da00f78e00"
    - secretKey: OWNCLOUD_ADMIN_USERNAME
      remoteRef:
        key: "98190bec-ce0a-4d12-a79d-b2da00f74354"
    - secretKey: OWNCLOUD_ADMIN_PASSWORD
      remoteRef:
        key: "0bd5f158-2ead-46bf-af68-b2da00f7018e"