apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: owncloud-files-pvc
  namespace: owncloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: syno-nfs
  resources:
    requests:
      storage: 20Gi