---
# packages to install
bind_zone_manager_packages:
  - bind9
  - bind9-utils
  - bind9-doc
  - dnsutils

# where to publish zones on the target
bind_zone_manager_zone_dir: /etc/bind/zones

# list of zones, each with its own A- and CNAME-records
# override this in your playbook or group_vars
bind_zone_manager_zone_defs: []

# reverse-zone definitions
bind_zone_manager_reverse_zone_defs: []

# network ACLs
bind_zone_manager_network: 0.0.0.0/0
bind_zone_manager_listen_ips:
  - 127.0.0.1

# list of upstream DNS forwarders
bind_zone_manager_forwarders:
  - 1.1.1.1
  - 8.8.8.8